/**
 * PUBLIC ROUTE PATTERNS — the data half of `src/proxy.ts`.
 *
 * ⚠️ THESE LIVE IN THEIR OWN MODULE SO A TEST CAN READ THEM. `proxy.ts` calls
 * `clerkMiddleware()` at module scope, so importing it from a unit test drags
 * in Clerk's whole request pipeline; these arrays are inert data and import
 * anywhere. `src/__tests__/marketing-routes.test.ts` walks
 * `content/marketing/nav.ts` against them and fails if a page the site links to
 * is not reachable by a signed-out visitor — the defect that shipped
 * `/solutions`, `/methodology`, `/security`, `/integrations` and `/changelog`
 * behind the login wall while every one of them was in the header menu.
 *
 * Patterns are Clerk `createRouteMatcher` syntax (path-to-regexp).
 */

/** Routes reachable without a session. Everything else requires auth. */
export const PUBLIC_ROUTE_PATTERNS: string[] = [
  "/",
  "/features(.*)",
  "/how-it-works",
  "/pricing",
  "/free-scanner(.*)",
  "/blog(.*)",
  "/guides(.*)",
  "/resources",
  "/about",
  "/contact",
  "/legal(.*)",
  "/bot",
  /*
   * ⚠️ THESE SIX WERE MISSING, AND EVERY ONE OF THEM IS LINKED FROM THE
   * HOMEPAGE. A marketing route absent from this list is not "slightly less
   * public" — `auth.protect()` bounces it to /login, so a prospect clicking
   * "Solutions" in the header got a sign-in form and Googlebot got a redirect.
   *
   * `marketing-routes.test.ts` now walks `content/marketing/nav.ts` and fails
   * if any navigable public path is not matched here, because the failure mode
   * is invisible in review: the page renders perfectly in isolation.
   */
  "/solutions(.*)",
  "/methodology",
  "/security",
  "/integrations",
  "/changelog",
  // Generated by `src/app/sitemap.ts` and `src/app/robots.ts`. A crawler sends
  // no session, so gating these hides the whole site from search.
  "/sitemap.xml",
  "/robots.txt",
  "/login(.*)",
  "/signup(.*)",
  "/invite(.*)",
  "/api/webhooks(.*)",
  "/api/public(.*)",
  "/api/v1(.*)",
  // Liveness and readiness probes are called by the platform with no session.
  // Gating these behind auth makes every deploy fail its health check.
  "/api/health(.*)",
  /*
   * A shared report link is a bearer credential handed to someone outside the
   * agency — the token IS the authorisation (§6.8). It resolves exactly one
   * report and lives outside every authenticated route group.
   */
  "/reports/shared(.*)",
];

/**
 * ⚠️ THE STATICALLY PRERENDERED MARKETING PAGES. §3.2 requires them to be
 * static and they are (`○` in the build output) — which is exactly why they
 * cannot take a nonce. See `contentSecurityPolicy` below.
 */
export const STATIC_MARKETING_PATTERNS: string[] = [
  "/",
  "/features(.*)",
  "/how-it-works",
  "/pricing",
  "/free-scanner",
  "/blog(.*)",
  "/guides(.*)",
  "/resources",
  "/about",
  "/contact",
  "/legal(.*)",
  "/bot",
  "/solutions(.*)",
  "/methodology",
  "/security",
  "/integrations",
  "/changelog",
  "/sitemap.xml",
  "/robots.txt",
];
