import { unsafeGlobalClient } from "@pdm/database";
import { classify, computeScore, evaluateRules, type VendorPattern } from "@pdm/analysis";
import { runScan } from "@pdm/scanner/scan";
import type { BrowserPool } from "@pdm/scanner/browser/pool";
import type { FreeScanJobData } from "@pdm/scanner/queue/queues";
import type { UrlGuard } from "@pdm/scanner/navigate";
import type { ConsentPhase, PhaseResult, ScanResult } from "@pdm/scanner/types";
import { childLogger } from "@pdm/shared/logger";
import { domainHash, track } from "@pdm/shared/analytics";
import type { Job } from "bullmq";

/**
 * THE FREE PUBLIC SCAN — PLAN.md Part III §3.2, Phase 6 task 6.5.
 *
 * ⚠️ NOTHING HERE WRITES A TENANT ROW. `FreeScan` is pre-tenant (§5.9): the
 * result lives as a JSON summary on that one global table and never touches
 * `Scan`, `Issue` or any evidence table. A free scan that created a `Scan` row
 * would need an `agencyId`, and inventing one would put an anonymous
 * stranger's submission inside a paying customer's tenant.
 *
 * ⚠️ THE ANALYSIS PIPELINE RUNS ENTIRELY IN MEMORY, and it is the SAME
 * pipeline — `classify`, `evaluateRules`, `computeScore` — that a paid scan
 * uses. That matters commercially as well as technically: the number on the
 * free result page is the number the product would give, so a visitor who
 * converts sees the same score rather than discovering the teaser was
 * generated by something simpler. All three functions are pure and take no
 * database, which is why this is possible at all.
 *
 * ⚠️ ONE PHASE, ONE PAGE, 45 SECONDS. §3.2's restriction table, verbatim, and
 * every line of it is a cost control on a surface anyone on the internet can
 * trigger. The four-phase journey is the paid value; giving it away here both
 * quadruples our cost and removes the reason to buy.
 */

const db = unsafeGlobalClient(
  // Justification (required in review): the free scanner is pre-tenant by
  // definition (§5.9). `FreeScan`, `FreeScanBlocklist` and `TrackerVendor` are
  // all global tables; no tenant data is read or written.
  "the free scanner is pre-tenant; FreeScan, its blocklist and the vendor catalogue are global",
);

/** §3.2: `no-consent` only. */
const FREE_PHASES: readonly ConsentPhase[] = ["NO_CONSENT"];
/** §3.2: "Timeout — 45 s hard". */
const FREE_TIMEOUT_MS = 45_000;
/** §3.2: "full detail on top 3 by severity". */
const DETAILED_FINDINGS = 3;
/** §3.2: "automatic block after 3 consecutive failures on a domain". */
const AUTO_BLOCK_AFTER_FAILURES = 3;

const SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW"] as const;

/**
 * What the public result page renders. PLAN.md §3.2's result-page list.
 *
 * ⚠️ THIS SHAPE IS THE DISCLOSURE BOUNDARY. Feature doc 18: "Domain + tracker
 * name only; no full URLs, no cookie values — prevents scraping our detection
 * logic." Everything the page can show has to be in here, so the redaction is
 * one reviewable type rather than a judgement made in JSX. There is
 * deliberately no field for a request URL, a cookie value, a rule id, a
 * fingerprint or a confidence score.
 */
export interface FreeScanSummary {
  cmpDetected: boolean;
  cmpName: string | null;
  trackersBeforeConsent: number;
  /** Vendor NAMES only, at most three. */
  topTrackers: string[];
  cookiesBeforeConsent: number;
  thirdPartyDomains: number;
  /** Every finding is counted; only the top three are described. */
  findingCount: number;
  topFindings: Array<{ severity: string; title: string }>;
  partial: boolean;
}

export interface FreeScanDeps {
  pool: BrowserPool;
  scannerVersion: string;
  workerId: string;
  /**
   * ⚠️ THE SSRF GUARD, INJECTABLE FOR FIXTURES ONLY (§10.3 R4/R5). §4.15's
   * fixtures are served from `127.0.0.1`, which the guard blocks by design and
   * must keep blocking on this surface above all others. Omitting it uses the
   * real guard, so the production wiring in `worker/src/index.ts` — which does
   * omit it — fails CLOSED.
   */
  urlGuard?: UrlGuard;
}

export async function processFreeScan(
  job: Job<FreeScanJobData>,
  deps: FreeScanDeps,
): Promise<{ status: string }> {
  const log = childLogger({ jobId: job.id, freeScanId: job.data.freeScanId });

  await db.freeScan.update({
    where: { id: job.data.freeScanId },
    data: { status: "RUNNING", startedAt: new Date() },
  });

  let result: ScanResult;
  try {
    result = await runScan(
      {
        /*
         * ⚠️ SYNTHETIC IDS. `runScan` wants a ScanInput and none of these three
         * ids is ever persisted — they exist so the recorder can label its own
         * in-memory structures. The free scan id is used for all of them so a
         * log line from inside the scanner is still traceable.
         */
        scanId: job.data.freeScanId,
        websiteId: job.data.freeScanId,
        agencyId: job.data.freeScanId,
        url: job.data.url,
        registrableDomain: job.data.registrableDomain,
        monitoredPaths: ["/"],
        // §10.3: robots is respected here exactly as it is for a paid scan.
        respectRobots: true,
        blockMedia: true,
        phases: FREE_PHASES,
        timeoutMs: FREE_TIMEOUT_MS,
      },
      deps,
    );
  } catch (error) {
    log.error({ err: error }, "free scan threw");
    await finish(job.data, "FAILED", null, null, "SCAN_ERROR");
    return { status: "FAILED" };
  }

  if (result.status === "FAILED") {
    /*
     * ⚠️ THE ERROR CODE IS STORED RAW AND MAPPED TO COPY AT RENDER TIME. §3.2
     * lists six distinct error states and requires five of them to be specific
     * and helpful; storing a pre-rendered sentence would make that mapping
     * impossible to change and would bake an English string into a data row.
     */
    await finish(job.data, "FAILED", null, null, result.errorCode ?? "UNKNOWN");
    return { status: "FAILED" };
  }

  const { summary, score } = await summarise(result, job.data.url);
  await finish(job.data, result.status, summary, score, null);

  // §9.6's funnel: submitted → completed → result_viewed → signup_clicked.
  // Hashed domain only — see the note at the submission end.
  void track("free_scan_completed", {
    domain_hash: domainHash(job.data.registrableDomain),
    score,
    status: result.status,
  });

  return { status: result.status };
}

/**
 * Runs the real analysis pipeline over the in-memory recording.
 *
 * ⚠️ ONE PHASE MEANS THE CONSENT RULES CANNOT FIRE, AND THAT IS CORRECT. Most
 * of §4.11's rules compare behaviour across phases — "still firing after Reject
 * All" needs a Reject All. `executed(context, phase)` returns false for every
 * phase we did not run, and every rule consults it first, so a single-phase
 * scan produces only the findings a single phase can support. The gap between
 * that and the full picture is precisely what the locked panel advertises.
 */
async function summarise(
  result: ScanResult,
  /**
   * ⚠️ THE SCANNED URL, AND IT IS NOT OPTIONAL. The first version passed `""`
   * here and PDM-R022 — which distinguishes "this page was reached over an
   * insecure connection" from "a secure page pulled an insecure subresource" —
   * silently took the second branch for every free scan. Same severity, same
   * score, wrong sentence: a plain-HTTP site was told its *subresources* were
   * the problem. A rule fact that is cheap to pass and easy to leave blank is
   * exactly the kind that produces a confidently wrong finding.
   */
  url: string,
): Promise<{ summary: FreeScanSummary; score: number }> {
  const vendors = await loadVendors();

  const phase = result.phases.find((candidate) => candidate.phase === "NO_CONSENT");
  const requests = phase?.requests ?? [];
  const cookies = phase?.cookies ?? [];
  const storage = phase?.storage ?? [];

  const detections = classify({
    vendors,
    requests: requests as never,
    cookies: cookies as never,
    storage: storage as never,
  });

  const phases: PhaseResult[] = result.phases;
  const findings = evaluateRules({
    phases,
    detections,
    vendorsById: new Map(vendors.map((vendor) => [vendor.id, vendor])),
    requests: requests as never,
    cookies: cookies as never,
    storage: storage as never,
    scan: {
      status: result.status,
      errorCode: result.errorCode,
      url,
      consecutiveFailures: 0,
      cmpId: result.cmp?.cmpId ?? null,
      cmpName: result.cmp?.cmpName ?? null,
    },
  });

  const vendorName = new Map(vendors.map((vendor) => [vendor.id, vendor.name]));
  const known = detections.filter((detection) => detection.vendorId !== null);

  const ranked = [...findings].sort(
    (a, b) =>
      SEVERITY_ORDER.indexOf(a.severity as never) -
      SEVERITY_ORDER.indexOf(b.severity as never),
  );

  /*
   * ⚠️ THE SCORE IS COMPUTED HERE, FROM **ALL** THE FINDINGS AND THE **REAL**
   * PHASES. Both halves were wrong in the first version and both were wrong in
   * the direction that misprices the product:
   *
   *   - Scoring from `topFindings` (the three shown) means a site with twelve
   *     issues scores the same as one with three. The free result would flatter
   *     the worst sites, which are the ones most worth converting.
   *   - Passing `phases: []` told the engine that NO phase executed, so it
   *     applied the incompleteness penalty to every free scan — a genuinely
   *     clean page came back 95 instead of 100, and the first thing a visitor
   *     would do is not believe us.
   *
   * The engine's `confidence` is PARTIAL for a one-phase scan either way, which
   * is correct and is why the page says so.
   */
  const score = computeScore({ findings, phases });

  const summary: FreeScanSummary = {
    cmpDetected: result.cmp !== null,
    cmpName: result.cmp?.cmpName ?? null,
    trackersBeforeConsent: known.length,
    topTrackers: known
      /*
       * ⚠️ HIGHEST CONFIDENCE FIRST, and NAMES ONLY. Showing "Meta Pixel,
       * Google Analytics, Hotjar" is credible and worth nothing to a
       * competitor; showing the matched pattern or the request that proved it
       * hands over the detection logic feature doc 18 says to protect.
       */
      .sort((a, b) => b.confidence - a.confidence)
      .slice(0, DETAILED_FINDINGS)
      .map((detection) => vendorName.get(detection.vendorId ?? "") ?? "Unknown")
      .filter((name, index, all) => all.indexOf(name) === index),
    cookiesBeforeConsent: cookies.length,
    thirdPartyDomains: new Set(
      requests
        .filter((request) => request.isThirdParty)
        .map((request) => request.registrableDomain),
    ).size,
    // Every finding is COUNTED — the gap between the count and the three
    // described is the conversion argument (§3.2).
    findingCount: findings.length,
    topFindings: ranked.slice(0, DETAILED_FINDINGS).map((finding) => ({
      severity: finding.severity,
      title: finding.title,
    })),
    partial: result.status === "PARTIAL",
  };

  return { summary, score: score.score };
}

/**
 * Writes the outcome and maintains the automatic blocklist.
 *
 * ⚠️ "3 CONSECUTIVE FAILURES", AND CONSECUTIVE IS CHECKED PROPERLY. Counting
 * failures in a window would block any site that had a bad week among many
 * successful scans; the last three ATTEMPTS all having failed is what §3.2
 * asks for, and a single success clears the automatic entry.
 */
async function finish(
  data: FreeScanJobData,
  status: string,
  summary: FreeScanSummary | null,
  score: number | null,
  errorCode: string | null,
): Promise<void> {
  await db.freeScan.update({
    where: { id: data.freeScanId },
    data: {
      status: status as never,
      finishedAt: new Date(),
      errorCode,
      healthScore: score,
      resultSummary: summary ? (summary as unknown as object) : undefined,
    },
  });

  if (status !== "FAILED") {
    // A success clears an AUTOMATIC block. A human-added one is never touched.
    await db.freeScanBlocklist.deleteMany({
      where: { registrableDomain: data.registrableDomain, addedByUserId: null },
    });
    return;
  }

  const recent = await db.freeScan.findMany({
    where: { registrableDomain: data.registrableDomain },
    orderBy: { createdAt: "desc" },
    take: AUTO_BLOCK_AFTER_FAILURES,
    select: { status: true },
  });
  const allFailed =
    recent.length === AUTO_BLOCK_AFTER_FAILURES &&
    recent.every((row) => row.status === "FAILED");
  if (!allFailed) return;

  await db.freeScanBlocklist.upsert({
    where: { registrableDomain: data.registrableDomain },
    create: {
      registrableDomain: data.registrableDomain,
      reason: `${AUTO_BLOCK_AFTER_FAILURES} consecutive failed scans`,
      failureCount: AUTO_BLOCK_AFTER_FAILURES,
    },
    // ⚠️ `addedByUserId` untouched: an automatic re-block must never erase the
    // record that a human made this decision, or an admin's note vanishes.
    update: { failureCount: AUTO_BLOCK_AFTER_FAILURES },
  });
}

async function loadVendors(): Promise<VendorPattern[]> {
  const vendors = await db.trackerVendor.findMany({ where: { isActive: true } });
  return vendors.map((vendor) => ({
    id: vendor.id,
    slug: vendor.slug,
    name: vendor.name,
    category: vendor.category,
    riskLevel: vendor.riskLevel,
    domainPatterns: vendor.domainPatterns,
    scriptPatterns: vendor.scriptPatterns,
    cookiePatterns: vendor.cookiePatterns,
    storagePatterns: vendor.storagePatterns,
    requestPathPatterns: vendor.requestPathPatterns,
    baseConfidence: vendor.baseConfidence,
    isEssentialCandidate: vendor.isEssentialCandidate,
  }));
}
