import { describe, expect, it } from "vitest";
import { createRouteMatcher } from "@clerk/nextjs/server";
import { NextRequest } from "next/server";
import { FOOTER_NAV, HEADER_NAV } from "@content/marketing/nav";
import { INDUSTRIES } from "@content/marketing/industries";
import { PUBLIC_ROUTE_PATTERNS, STATIC_MARKETING_PATTERNS } from "@/lib/public-routes";

/**
 * ⚠️ THIS FILE EXISTS BECAUSE THE BUG IT PREVENTS WAS INVISIBLE IN REVIEW.
 *
 * `/solutions`, `/solutions/[industry]` (×5), `/methodology`, `/security`,
 * `/integrations` and `/changelog` all shipped as finished marketing pages —
 * written, styled, linked from the header and the footer, rendering perfectly
 * when opened directly in `next dev` by someone who was signed in.
 *
 * They were also absent from `isPublicRoute` in `src/proxy.ts`, so
 * `auth.protect()` bounced every signed-out visitor to /login. A prospect
 * clicking "Solutions" got a sign-in form; Googlebot got a redirect and
 * indexed nothing. Ten links on the homepage were dead and every one of them
 * looked alive to the person who wrote them.
 *
 * Nothing about a page's own source says whether the proxy lets a stranger
 * reach it. The two facts live in different files and only the pairing is
 * wrong, which is exactly the shape of defect a test has to hold.
 */

/** Builds the request Clerk's matcher expects. */
function request(path: string) {
  return new NextRequest(new URL(path, "http://localhost:3000"));
}

const isPublic = createRouteMatcher(PUBLIC_ROUTE_PATTERNS);
const isStaticMarketing = createRouteMatcher(STATIC_MARKETING_PATTERNS);

/** Every internal href a visitor can click from the site chrome. */
function navigablePaths(): string[] {
  const fromGroups = [...HEADER_NAV, ...FOOTER_NAV].flatMap((group) =>
    group.items.map((item) => item.href),
  );

  return [...new Set(fromGroups)]
    // In-page anchors ("/#drift") resolve to a page already covered elsewhere.
    .filter((href) => href.startsWith("/") && !href.startsWith("/#"))
    .map((href) => href.split("#")[0]!);
}

/**
 * The subset that is a rendered PAGE.
 *
 * The footer links `/api/health/ready` as a status endpoint. It must be public
 * — and it is, via `/api/health(.*)` — but it is a route handler returning
 * JSON, so the marketing CSP policy is neither needed nor appropriate for it.
 */
function navigablePagePaths(): string[] {
  return navigablePaths().filter((path) => !path.startsWith("/api/"));
}

describe("marketing routes are reachable by a signed-out visitor", () => {
  it.each(navigablePaths())(
    "%s — linked from the site chrome, so it must be public",
    (path) => {
      expect(isPublic(request(path))).toBe(true);
    },
  );

  it.each(INDUSTRIES.map((industry) => `/solutions/${industry.slug}`))(
    "%s — generated by generateStaticParams, so it must be public",
    (path) => {
      expect(isPublic(request(path))).toBe(true);
    },
  );

  it("exposes the crawler entry points", () => {
    expect(isPublic(request("/sitemap.xml"))).toBe(true);
    expect(isPublic(request("/robots.txt"))).toBe(true);
  });
});

describe("the static-marketing CSP policy covers the same pages", () => {
  /*
   * A public page missing from STATIC_MARKETING_PATTERNS still renders, but it
   * gets the strict nonce policy — and its inline bootstrap script, baked into
   * the prerendered HTML, carries no nonce. The page loads with its scripts
   * refused, which is a blank interactive surface rather than an error.
   */
  it.each(navigablePagePaths())("%s gets the static policy", (path) => {
    expect(isStaticMarketing(request(path))).toBe(true);
  });
});

describe("authenticated surfaces stay gated", () => {
  it.each(["/app", "/app/websites", "/admin", "/admin/agencies", "/app/settings/billing"])(
    "%s is not public",
    (path) => {
      expect(isPublic(request(path))).toBe(false);
    },
  );

  it("does not hand the weak static policy to any authenticated surface", () => {
    for (const path of ["/app", "/admin", "/portal/issues", "/free-scanner/abc123"]) {
      expect(isStaticMarketing(request(path))).toBe(false);
    }
  });
});
