/**
 * REPORT COPY — PLAN.md Part VI §6.8, Part I §1.12, Part XI §11.11.
 *
 * ⚠️ SEPARATED FROM THE TEMPLATES so a locale is a copy file, not a rewrite —
 * the same rule as `packages/email/src/copy/en.ts`.
 *
 * ⚠️ A PDF IS THE ARTEFACT MOST LIKELY TO BE FORWARDED OUTSIDE THE AGENCY, and
 * therefore the one where positioning language does the most damage. Everything
 * here reports what was DETECTED. Nothing asserts a regulatory conclusion.
 */

export const reportCopy = {
  cover: {
    kicker: "Privacy & consent monitoring",
    preparedFor: "Prepared for",
    preparedBy: "Prepared by",
    period: "Reporting period",
    generated: "Generated",
    website: "Website",
  },

  types: {
    SCAN: "Scan report",
    ISSUE: "Findings report",
    MONTHLY_MONITORING: "Monthly monitoring report",
    WEBSITE_HEALTH: "Website health report",
    PRIVACY_DRIFT: "Privacy drift report",
  },

  sections: {
    summary: "Summary",
    methodology: "How this was measured",
    limitations: "What this does not cover",
    consentMatrix: "Consent journeys",
    trackers: "Tracking services detected",
    cookies: "Cookies observed",
    issues: "Potential issues",
    resolvedIssues: "Resolved during this period",
    drift: "What changed",
    score: "Privacy health score",
    scoreBreakdown: "How the score was reached",
    scans: "Monitoring activity",
    perWebsite: "By website",
    evidence: "Technical evidence",
    appendix: "Evidence appendix",
    screenshots: "Screenshots",
    aiSummary: "Summary",
  },

  labels: {
    severity: "Severity",
    status: "Status",
    detected: "Detected",
    firstDetected: "First detected",
    lastSeen: "Last seen",
    category: "Category",
    vendor: "Service",
    risk: "Risk",
    domains: "Domains",
    cookie: "Cookie",
    domain: "Domain",
    lifetime: "Lifetime",
    session: "Session",
    days: "days",
    before: "Before",
    after: "After",
    change: "Change",
    website: "Website",
    score: "Score",
    openIssues: "Open findings",
    lastScanned: "Last checked",
    recommendation: "Review recommended",
    technicalReason: "What we observed",
    evidenceRef: "Evidence",
    page: "Page",
    of: "of",
    beforeConsent: "Fired before consent",
    afterReject: "Set before consent",
    yes: "Yes",
    no: "No",
  },

  outcomes: {
    detected: "Detected",
    notDetected: "Not detected",
    unknown: "Could not be determined",
  },

  summary: {
    scansPerformed: "Scans performed",
    monitoringUptime: "Scans completed successfully",
    websitesMonitored: "Websites monitored",
    issuesOpened: "Findings opened",
    issuesResolved: "Findings resolved",
    changesDetected: "Changes detected",
    currentScore: "Current privacy health score",
    requests: "Network requests recorded",
    thirdPartyRequests: "Third-party requests",
    preConsentRequests: "Requests before consent",
  },

  empty: {
    issues: "No potential issues were detected in this period.",
    drift: "No changes were detected in this period.",
    trackers: "No tracking services were detected.",
    cookies: "No cookies were observed.",
    scans: "No scans ran in this period.",
    evidence: "No evidence records are attached to this finding.",
  },

  /**
   * ⚠️ THE PARTIAL NOTICE. P5 — an incomplete scan may never produce a clean
   * verdict, and a PDF is where that rule is easiest to break silently, because
   * the reader cannot click through to find out.
   */
  partial: {
    heading: "Some consent journeys could not be completed",
    body:
      "Parts of this scan did not finish, so the results below are incomplete. " +
      "Anything that depends on a journey that did not run is reported as " +
      "“could not be determined” rather than as a clean result.",
    phasesLabel: "Journeys not completed",
  },

  limitations: [
    "Findings describe behaviour observed in a headless browser at a point in time. Behaviour can differ for real visitors, by geography, and by device.",
    "Tags loaded only after a user interaction we do not perform may not appear.",
    "Server-side tracking is not visible to a browser-based scan.",
    "Consent journeys depend on the consent banner being detectable and operable automatically.",
  ],

  footer: {
    generatedBy: "Generated by",
    confidential: "Confidential — prepared for the named recipient.",
  },
} as const;

export type ReportCopy = typeof reportCopy;
